<?php
/**
 * HiPay Fullservice Magento - Hyvä Checkout
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Apache 2.0 Licence
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * @copyright Copyright (c) 2024 - HiPay
 * @license   http://www.apache.org/licenses/LICENSE-2.0 Apache 2.0 Licence
 */

declare(strict_types=1);

use HiPay\FullserviceHyvaCheckout\Magewire\CardMethod;
use HiPay\FullserviceHyvaCheckout\ViewModel\Config;
use HiPay\FullserviceMagento\Model\Method\HostedFieldsMethod;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;

/** @var ViewModelRegistry $viewModels */
/** @var CardMethod $magewire */
/** @var Escaper $escaper */

$configViewModel = $viewModels->require(Config::class);
$customerInfo = $magewire->customerInformation;
$oneClickEnabled = (bool) $configViewModel->getOneClickEnabled(HostedFieldsMethod::HIPAY_METHOD_CODE);
$customerCards = $configViewModel->getCustomerCards();
?>
<div
    x-data="hipayCheckoutHostedFields"
    data-method="<?= $escaper->escapeHtmlAttr(HostedFieldsMethod::HIPAY_METHOD_CODE) ?>"
    data-wire-id="<?= $escaper->escapeHtmlAttr($magewire->getId()) ?>"
    data-cc-config="<?=
    $escaper->escapeHtmlAttr(
        $configViewModel->getSerializedCreditCardConfig(HostedFieldsMethod::HIPAY_METHOD_CODE)
    ) ?>"
    data-general-config="<?= $escaper->escapeHtmlAttr($configViewModel->getSerializedConfig()) ?>"
    data-customer-info="<?= $escaper->escapeHtmlAttr(json_encode($customerInfo)) ?>"
    data-customer-cards="<?= $escaper->escapeHtmlAttr(json_encode($customerCards)) ?>"
>
    <div class="form hosted-fields-form" id="co-transparent-form">
        <div id="hipay-container-hosted-fields" class="bg-white !w-full">
            <?php if ($oneClickEnabled && $customerCards): ?>
                <div id="hipay-saved-cards"></div>
            <?php endif; ?>

            <div class="hipay-hosted-fields-form">
                <div class="hipay-row cc-row" wire:ignore>
                    <div class="hipay-field-container">
                        <div class="hipay-field" id="hipay-card-holder"></div>
                        <label class="hipay-label" for="hipay-card-holder">
                            <span><?= $escaper->escapeHtml(__('Card Owner Name')) ?></span>
                        </label>
                        <div class="hipay-baseline"></div>
                        <div
                            class="hipay-field-error absolute text-xs text-red-500"
                            data-hipay-id="hipay-card-field-error-cardHolder"
                        ></div>
                    </div>
                </div>

                <div class="hipay-row cc-row" wire:ignore>
                    <div class="hipay-field-container">
                        <div class="hipay-field" id="hipay-card-number"></div>
                        <label class="hipay-label" for="hipay-card-number">
                            <span><?= $escaper->escapeHtml(__('Card Number')) ?></span>
                        </label>
                        <div class="hipay-baseline"></div>
                        <div
                            class="hipay-field-error absolute text-xs text-red-500"
                            data-hipay-id="hipay-card-field-error-cardNumber"
                        ></div>
                    </div>
                </div>

                <div class="hipay-row cc-row" wire:ignore>
                    <div class="hipay-field-container hipay-field-container-half">
                        <div class="hipay-field" id="hipay-date-expiry"></div>
                        <label class="hipay-label" for="hipay-date-expiry">
                            <span><?= $escaper->escapeHtml(__('Expiry date')) ?></span>
                        </label>
                        <div class="hipay-baseline"></div>
                        <div
                            class="hipay-field-error absolute text-xs text-red-500"
                            data-hipay-id="hipay-card-field-error-expiryDate"
                        ></div>
                    </div>

                    <div class="hipay-field-container hipay-field-container-half" wire:ignore>
                        <div class="hipay-field" id="hipay-cvc"></div>
                        <label class="hipay-label" for="hipay-cvc">
                            <span><?= $escaper->escapeHtml(__('CVC')) ?></span>
                        </label>
                        <div class="hipay-baseline"></div>
                        <div
                            class="hipay-field-error absolute text-xs text-red-500"
                            data-hipay-id="hipay-card-field-error-cvc"
                        ></div>
                    </div>
                </div>

                <div class="hipay-elements-container cc-row" wire:ignore>
                    <div id="hipay-help-cvc"></div>
                </div>

                <div id="hipay-saved-card-button"></div>

                <div class="field cc-row save-cc hidden" wire:ignore>
                    <div class="control">
                        <input
                            type="checkbox"
                            name="payment[create_oneclick]"
                            class="checkbox"
                            id="hipay_hosted_fields_create_oneclick"
                        />
                        <label class="label" for="hipay_hosted_fields_create_oneclick">
                            <span><?= $escaper->escapeHtml(__('Save this card for future use')) ?></span>
                        </label>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
