<?php
/**
 * HiPay Fullservice Magento - Hyvä Checkout
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Apache 2.0 Licence
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * @copyright Copyright (c) 2024 - HiPay
 * @license   http://www.apache.org/licenses/LICENSE-2.0 Apache 2.0 Licence
 */

declare(strict_types=1);

use HiPay\FullserviceHyvaCheckout\Magewire\CardMethod;
use HiPay\FullserviceHyvaCheckout\ViewModel\Config;
use HiPay\FullserviceMagento\Model\Method\HostedFieldsMethod;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;

/** @var ViewModelRegistry $viewModels */
/** @var CardMethod $magewire */
/** @var Escaper $escaper */

$configViewModel = $viewModels->require(Config::class);
$customerInfo = $magewire->getCustomerInformation();
$oneClickEnabled = $configViewModel->getOneClickEnabled(HostedFieldsMethod::HIPAY_METHOD_CODE);
$customerCards = $configViewModel->getCustomerCards();
?>

<div>
    <script>
        (() => {
            const HIPAY_METHOD_HOSTED_FIELDS = '<?= HostedFieldsMethod::HIPAY_METHOD_CODE ?>';
            const HIPAY_METHOD_HOSTED_FIELDS_WIRE_ID = '<?= /* @NoEscape */ $magewire->getId() ?>';
            if (!window.hipayHostedFieldsInitialized) {
                window.addEventListener('checkout:payment:method-activate', (event) => {
                    if (event.detail && event.detail.method === HIPAY_METHOD_HOSTED_FIELDS) {
                        hyvaCheckout.payment.activate(HIPAY_METHOD_HOSTED_FIELDS, {
                            hiPayCcConfig: <?= /* @noEscape */ $configViewModel->getSerializedCreditCardConfig(HostedFieldsMethod::HIPAY_METHOD_CODE) ?>,
                            hiPayGeneralConfig: <?= /* @noEscape */ $configViewModel->getSerializedConfig() ?>,
                            selectors: {},
                            component: {
                                createOneclick: false,
                                showCcForm: true,
                                env: '',
                                apiUsernameTokenJs: '',
                                apiPasswordTokenJs: '',
                                locale: 'en',
                                sdkJsUrl: '',
                                hipayHostedFields: null,
                                configHipay: null,
                                hipayHFstatus: false,
                                isPlaceOrderAllowed: false,
                                placeOrderBtn: '',
                                eci: '',
                            },
                            async initialize() {
                                if (this.el) {
                                    this._initComponent();
                                    this._initFieldsData();
                                    this._initHostedFields();
                                    this._bindFields();
                                }
                            },
                            _bindFields() {
                                this.selectors.oneClickContainer.addEventListener('click', (event) => {
                                    const oneClickCheckbox = this.selectors.oneClickContainer.querySelector('input[type="checkbox"]')
                                    this._updateOneClick(oneClickCheckbox.checked);
                                });
                            },

                            _initComponent() {
                                const { hipay_hosted_fields } = this.hiPayCcConfig.payment;
                                const { hiPayFullservice } = this.hiPayGeneralConfig.payment;
                                this.component.placeOrderBtn = document.querySelector('.btn-place-order');

                                if (hipay_hosted_fields) {
                                    this.component = {
                                        ...this.component,
                                        ...{
                                            env: hipay_hosted_fields.env,
                                            apiUsernameTokenJs: hipay_hosted_fields.apiUsernameTokenJs,
                                            apiPasswordTokenJs: hipay_hosted_fields.apiPasswordTokenJs,
                                            sdkJsUrl: hipay_hosted_fields.sdkJsUrl,
                                            oneClick: {
                                                enabled: hipay_hosted_fields.useOneClick,
                                                maxCard: hipay_hosted_fields.oneClickMaxCards,
                                                selectedCard: '',
                                            },
                                            cardTypes: {
                                                availableTypes: hipay_hosted_fields.availableTypes,
                                                icons: hipay_hosted_fields.icons
                                            },
                                            style: {
                                                color: hipay_hosted_fields.color,
                                                fontFamily: hipay_hosted_fields.fontFamily,
                                                fontSize: hipay_hosted_fields.fontSize,
                                                fontWeight: hipay_hosted_fields.fontWeight,
                                                placeholderColor: hipay_hosted_fields.placeholderColor,
                                                caretColor: hipay_hosted_fields.caretColor,
                                                iconColor: hipay_hosted_fields.iconColor,
                                                oneClickHighlightColor: hipay_hosted_fields.oneClickHighlightColor,
                                                oneClickToggleColor: hipay_hosted_fields.oneClickToggleColor,
                                            }
                                        }
                                    }
                                }

                                if (hiPayFullservice) {
                                    this.component = {
                                        ...this.component,
                                        ...{
                                            locale: hiPayFullservice.locale.hipay_hosted_fields,
                                            useOneClick: hiPayFullservice.useOneclick.hipay_hosted_fields
                                        }
                                    }
                                }

                                this.selectors = {
                                    oneClickContainer: document.querySelector('#hipay-saved-card-button')
                                };

                                if (this.component.placeOrderBtn) {
                                    this.component.placeOrderBtn.removeAttribute('disabled');
                                }
                            },

                            _initFieldsData() {
                                let customerFirstName = '',
                                    customerLastName = '';

                                const billingAddress = <?= /* @NoEscape */ json_encode($customerInfo) ?>;

                                if (billingAddress) {
                                    customerFirstName = billingAddress.firstName;
                                    customerLastName = billingAddress.lastName;
                                }

                                const hostedFieldsStyle = this.component.style;
                                this.component.configHipay = {
                                    selector: 'hipay-container-hosted-fields',
                                    brand: this._getAvailableBrands(this.component.cardTypes.availableTypes),
                                    one_click: {
                                        enabled: this.component.oneClick.enabled,
                                        cards_display_count: this.component.oneClick.maxCard,
                                        cards: <?= json_encode($customerCards) ?>
                                    },
                                    fields: {
                                        savedCards: {
                                            selector: 'hipay-saved-cards'
                                        },
                                        cardHolder: {
                                            selector: 'hipay-card-holder',
                                            defaultFirstname: customerFirstName,
                                            defaultLastname: customerLastName
                                        },
                                        cardNumber: {
                                            selector: 'hipay-card-number'
                                        },
                                        expiryDate: {
                                            selector: 'hipay-date-expiry'
                                        },
                                        cvc: {
                                            selector: 'hipay-cvc',
                                            helpButton: true,
                                            helpSelector: 'hipay-help-cvc'
                                        },
                                        savedCardButton: {
                                            selector: 'hipay-saved-card-button'
                                        }
                                    },
                                    styles: {
                                        base: {
                                            fontFamily: hostedFieldsStyle.fontFamily,
                                            color: hostedFieldsStyle.color,
                                            fontSize: hostedFieldsStyle.fontSize,
                                            fontWeight: hostedFieldsStyle.fontWeight,
                                            placeholderColor: hostedFieldsStyle.placeholderColor,
                                            caretColor: hostedFieldsStyle.caretColor,
                                            iconColor: hostedFieldsStyle.iconColor
                                        },
                                        components: {
                                            switch: {
                                                mainColor: hostedFieldsStyle.oneClickToggleColor
                                            },
                                            checkbox: {
                                                mainColor: hostedFieldsStyle.oneClickHighlightColor
                                            }
                                        }
                                    }
                                };
                            },

                            _customerHasCard: function () {
                                const customerCards = <?= json_encode($customerCards) ?>;
                                const availableBrands = this._getAvailableBrands(this.component.cardTypes.availableTypes);

                                return (
                                    customerCards.length > 0 &&
                                    customerCards.some((card) => availableBrands.includes(card.brand))
                                );
                            },

                            _initHostedFields() {
                                if (window.hipaySdk) {
                                    this._createHostedFields();
                                } else {
                                    this._initHipaySdk();
                                    this._createHostedFields();
                                }
                            },

                            _getAvailableBrands(brand) {
                                let result = new Set();

                                Object.entries(brand).forEach(([key, value]) => {
                                    switch (key) {
                                        case 'VI':
                                            result.add('visa');
                                            result.add('cb');
                                            break;
                                        case 'MC':
                                            result.add('mastercard');
                                            break;
                                        case 'AE':
                                            result.add('american-express');
                                            break;
                                        case 'MI':
                                            result.add('maestro');
                                            result.add('bcmc');
                                            break;
                                    }
                                });
                                return Array.from(result);
                            },

                            _setupSavedCards: function () {
                                const savedCardsContainer =
                                    document.getElementById('hipay-saved-cards');
                                if (savedCardsContainer &&
                                    savedCardsContainer.querySelector('.saved-card')
                                ) {
                                    this._bindSavedCardsEvents();
                                }
                            },

                            _createHostedFields() {
                                this.component.hipayHostedFields = window.hipaySdk.create('card', this.component.configHipay);
                                this._bindHostedFields();
                                this.showCcForm = this.component.oneClick.enabled && this._customerHasCard();
                            },

                            _bindHostedFields() {
                                this.component.hipayHostedFields.on('ready', (data) => {
                                    this._toggleCardForm();
                                    this._setupSavedCards();
                                    const payOtherCard = document.querySelector('#pay-other-card');
                                    if (payOtherCard) {
                                        payOtherCard.click();
                                    }
                                });

                                this.component.hipayHostedFields.on('change', (data) => {
                                    if (this.component.showCcForm) {
                                        if (!data.valid || data.error) {
                                            this.component.hipayHFstatus = false;
                                        } else if (data.valid) {
                                            this.component.hipayHFstatus = true;
                                        }
                                        this.component.isPlaceOrderAllowed = this.component.hipayHFstatus;
                                    }
                                });

                                this.component.hipayHostedFields.on('blur', function (data) {
                                    // Get error container
                                    const domElement = document.querySelector(
                                        "[data-hipay-id='hipay-card-field-error-" + data.element + "']"
                                    );

                                    // Finish function if no error DOM element
                                    if (!domElement) {
                                        return;
                                    }

                                    // If not valid & not empty add error
                                    if (!data.validity.valid && !data.validity.empty) {
                                        domElement.innerText = data.validity.error;
                                    } else {
                                        domElement.innerText = '';
                                    }
                                });

                                this.component.hipayHostedFields.on('inputChange', function (data) {
                                    const domElement = document.querySelector(
                                        "[data-hipay-id='hipay-card-field-error-" + data.element + "']"
                                    );

                                    if (!domElement) {
                                        return;
                                    }

                                    if (!data.validity.valid && !data.validity.potentiallyValid) {
                                        domElement.innerText = data.validity.error;
                                    } else {
                                        domElement.innerText = '';
                                    }
                                });
                            },

                            _bindSavedCardsEvents () {
                                const savedCards = document.querySelectorAll('#hipay-saved-cards .saved-card');
                                savedCards.forEach((savedCard) => {
                                    savedCard.removeEventListener('click',  this._selectCard)
                                    savedCard.addEventListener('click', (e) => {
                                        this._selectCard(e, savedCard);
                                    });
                                })
                            },

                            _selectCard (e, savedCard) {
                                const $checkbox = savedCard.querySelector('input[type="checkbox"]');
                                const selectedCard = document.querySelector('.saved-card.checked');

                                if (!savedCard.querySelector('input[type="checkbox"]').checked) {
                                    this.component.oneClick.selectedCard = $checkbox.getAttribute('id');
                                    this.component.eci = this.hiPayGeneralConfig.payment.hiPayFullservice.recurringEci;
                                } else {
                                    this.component.eci = this.hiPayGeneralConfig.payment.hiPayFullservice.defaultEci;
                                }

                                if (!selectedCard && this.showCcForm) {
                                    const payOtherCard = document.querySelector('#pay-other-card');
                                    if (payOtherCard) {
                                        payOtherCard.click();
                                    }
                                }

                            },

                            _initHipaySdk() {
                                const lang = this.component.locale && this.component.locale.length > 2 ? this.component.locale.substr(0, 2) : 'en';

                                window.hipaySdk = new HiPay({
                                    username: this.component.apiUsernameTokenJs,
                                    password: this.component.apiPasswordTokenJs,
                                    environment: this.component.env,
                                    lang: lang
                                });
                            },

                            _updateOneClick(state) {
                                this.component.createOneclick = state;
                                this.component.hipayHostedFields.setMultiUse(this.component.useOneClick && state);
                            },

                            _toggleCardForm() {
                                const payOtherCard = document.querySelector('#pay-other-card');
                                const ccForm = document.querySelector('.hipay-hosted-fields-form');

                                if (payOtherCard) {
                                    payOtherCard.addEventListener('click', () => {
                                        const selectedCard = document.querySelector('.saved-card.checked');
                                        if (this.showCcForm) {
                                            this.showCcForm = !this.showCcForm;
                                            ccForm.style.display = 'none';
                                           return;
                                        }

                                        if (selectedCard) {
                                            selectedCard.click();
                                        }

                                        ccForm.style.display = 'block';
                                        this.showCcForm = !this.showCcForm;
                                    });
                                }
                            },

                            placeOrderViaJs() {
                                return true;
                            },

                            async placeOrder() {
                                if (this.component.oneClick.selectedCard === '') {
                                   this.component.eci = this.hiPayGeneralConfig.payment.hiPayFullservice.defaultEci
                                }

                                this.component.hipayHostedFields.getPaymentData().then(
                                    (response) => {
                                        if (response.one_click === true || response.multi_use === true) {
                                            this.component.eci = this.hiPayGeneralConfig.payment.hiPayFullservice.defaultEci;
                                        }
                                        if (response.token && response.payment_product && response.device_fingerprint) {
                                            Magewire.find(HIPAY_METHOD_HOSTED_FIELDS_WIRE_ID).call('setPaymentData', this._getPaymentData(response)).then(() => {
                                             hyvaCheckout.main.getWireComponent().placeOrder();
                                            });
                                        } else {
                                            throw response.error;
                                        }
                                    },
                                    (errors) => {
                                        for (let error in errors) {
                                            throw errors[error].error;
                                        }
                                    }
                                );
                            },

                            _getPaymentData (response) {
                                return {
                                    additionalData: {
                                        create_oneclick: response.one_click,
                                        card_token: response.token,
                                        payment_product: response.payment_product,
                                        cc_owner: response.card_holder,
                                        card_pan: response.pan,
                                        card_expiry_month: response.card_expiry_month,
                                        card_expiry_year: response.card_expiry_year,
                                        card_multi_use: response.multi_use,
                                        eci: this.component.eci,
                                        cc_type: response.payment_product,
                                        fingerprint:response. device_fingerprint
                                    },
                                }
                            }
                        }, document.getElementById('hipay-container-hosted-fields'));
                    }
                });

                window.hipayHostedFieldsInitialized = true;
            }
        })();

    </script>

    <div
        class="form hosted-fields-form"
        id="co-transparent-form">
        <div id="hipay-container-hosted-fields" class="bg-white !w-full">

            <?php if ($oneClickEnabled && $customerCards): ?>
                <div id="hipay-saved-cards"></div>
            <?php endif; ?>

            <div class="hipay-hosted-fields-form">
                <div class="hipay-row cc-row" wire:ignore>
                    <div class="hipay-field-container">
                        <div class="hipay-field" id="hipay-card-holder"></div>
                        <label class="hipay-label" for="hipay-card-holder">
                            <span> <?= $escaper->escapeHtml(__('Card Owner Name')) ?></span>
                        </label>
                        <div class="hipay-baseline"></div>
                        <div
                            class="hipay-field-error absolute text-xs text-red-500"
                            data-hipay-id="hipay-card-field-error-cardHolder"
                        ></div>
                    </div>
                </div>
                <div class="hipay-row cc-row" wire:ignore>
                    <div class="hipay-field-container">
                        <div class="hipay-field" id="hipay-card-number"></div>
                        <label class="hipay-label" for="hipay-card-number">
                            <span><?= $escaper->escapeHtml(__('Card Number')) ?></span>
                        </label>
                        <div class="hipay-baseline"></div>
                        <div
                            class="hipay-field-error absolute text-xs text-red-500"
                            data-hipay-id="hipay-card-field-error-cardNumber"
                        ></div>
                    </div>
                </div>
                <div class="hipay-row cc-row" wire:ignore>
                    <div class="hipay-field-container hipay-field-container-half">
                        <div class="hipay-field" id="hipay-date-expiry"></div>
                        <label class="hipay-label" for="hipay-date-expiry">
                            <span><?= $escaper->escapeHtml(__('Expiry date')) ?></span>
                        </label>
                        <div class="hipay-baseline"></div>
                        <div
                            class="hipay-field-error absolute text-xs text-red-500"
                            data-hipay-id="hipay-card-field-error-expiryDate"
                        ></div>
                    </div>
                    <div class="hipay-field-container hipay-field-container-half" wire:ignore>
                        <div class="hipay-field" id="hipay-cvc"></div>
                        <label class="hipay-label" for="hipay-cvc">
                            <span><?= $escaper->escapeHtml(__('CVC')) ?></span>
                        </label>
                        <div class="hipay-baseline"></div>
                        <div
                            class="hipay-field-error absolute text-xs text-red-500"
                            data-hipay-id="hipay-card-field-error-cvc"
                        ></div>
                    </div>
                </div>

                <div class="hipay-elements-container cc-row" wire:ignore>
                    <div id="hipay-help-cvc"></div>
                </div>

                <div id="hipay-saved-card-button"></div>
                <div class="field cc-row save-cc hidden" wire:ignore>
                    <div class="control">
                        <input
                            type="checkbox"
                            name="payment[create_oneclick]"
                            class="checkbox"
                            id="hipay_hosted_fields_create_oneclick"
                        />
                        <label class="label" for="hipay_hosted_fields_create_oneclick">
                            <span>
                                <?= $escaper->escapeHtml(__('Save this card for future use')) ?>
                            </span>
                        </label>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
