<?php
/**
 * HiPay Fullservice Magento - Hyvä Checkout
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Apache 2.0 Licence
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * @copyright Copyright (c) 2024 - HiPay
 * @license   http://www.apache.org/licenses/LICENSE-2.0 Apache 2.0 Licence
 */

declare(strict_types=1);

use HiPay\FullserviceHyvaCheckout\ViewModel\Config;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;

/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */
/** @var \Magento\Framework\View\Element\Template $block */

$configViewModel = $viewModels->require(Config::class);
$methodCode = (string) $block->getData('method_code');
?>
<div
    x-data="hipayCheckoutHostedIframe"
    data-method="<?= $escaper->escapeHtmlAttr($methodCode) ?>"
    data-general-config="<?= $escaper->escapeHtmlAttr($configViewModel->getSerializedConfig()) ?>"
>
    <div class="actions-toolbar iframe-continue mt-2" wire:ignore>
        <button type="button" class="btn btn-primary justify-center py-2.5">
            <span><?= $escaper->escapeHtml(__('Continue')) ?></span>
        </button>
    </div>

    <div class="iframe-container" style="display:none;" wire:ignore>
        <div class="message notice my-2">
            <span><?= $escaper->escapeHtml(__('Please do not refresh the page until you complete payment.')) ?></span>
        </div>
        <iframe
            class="hipay_hosted iframe"
            style="width:100%;display:block;border:0;"
            title="HiPay Hosted Page"
            sandbox="allow-modals allow-top-navigation allow-same-origin allow-scripts allow-forms"
        ></iframe>
    </div>
</div>
