<?php
/**
 * HiPay Fullservice Magento - Hyvä Checkout
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Apache 2.0 Licence
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * @copyright Copyright (c) 2024 - HiPay
 * @license   http://www.apache.org/licenses/LICENSE-2.0 Apache 2.0 Licence
 */

declare(strict_types=1);

use HiPay\FullserviceHyvaCheckout\Magewire\CardMethod;
use HiPay\FullserviceHyvaCheckout\ViewModel\Config;
use HiPay\FullserviceMagento\Model\Method\HostedMethod;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;

/** @var ViewModelRegistry $viewModels */
/** @var CardMethod $magewire */
/** @var Escaper $escaper */

$configViewModel = $viewModels->require(Config::class);

$methodCode = HostedMethod::HIPAY_METHOD_CODE;
$oneClickEnabled = (bool) $configViewModel->getOneClickEnabled($methodCode);
$customerCards = $configViewModel->getCustomerCards();
?>
<div
    x-data="hipayCheckoutHosted"
    data-method="<?= $escaper->escapeHtmlAttr($methodCode) ?>"
    data-wire-id="<?= $escaper->escapeHtmlAttr($magewire->getId()) ?>"
    data-general-config="<?= $escaper->escapeHtmlAttr($configViewModel->getSerializedConfig()) ?>"
    data-cc-config="<?= $escaper->escapeHtmlAttr($configViewModel->getSerializedCreditCardConfig($methodCode)) ?>"
    data-api-env="<?= $escaper->escapeHtmlAttr((string) $configViewModel->getApiEnv()) ?>"
    data-api-username-token-js="<?= $escaper->escapeHtmlAttr((string) $configViewModel->getApiUsernameTokenJs()) ?>"
    data-api-password-token-js="<?= $escaper->escapeHtmlAttr((string) $configViewModel->getApiPasswordTokenJs()) ?>"
>
    <div id="hipay-container-hosted">
        <div class="form" id="co-transparent-form">
            <input
                type="hidden"
                id="hosted-ioBBFingerPrint"
                name="payment[device_fingerprint]"
            />

            <?php if ($oneClickEnabled && $customerCards): ?>
                <div class="hipay-row cc-registered-row">
                    <div class="flex flex-col w-full items-start">
                        <label for="hipay_hosted_fields_cc_token" class="label">
                            <span><?= $escaper->escapeHtml(__('Your credit cards')) ?></span>
                        </label>
                        <div class="w-full">
                            <select
                                name="payment[cc_token]"
                                class="form-select w-full"
                                wire:model="selectedCustomerCard"
                                id="hipay_hosted_fields_cc_token"
                            >
                                <option value="">
                                    <?= $escaper->escapeHtml(__('Pay with a new card')) ?>
                                </option>
                                <?php foreach ($magewire->customerCards as $key => $customerCard): ?>
                                    <option value="<?= $escaper->escapeHtmlAttr($key) ?>">
                                        <?= $escaper->escapeHtml(
                                            $customerCard['brand'] . ' - ' . $customerCard['pan']
                                        ) ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                </div>
            <?php endif; ?>

            <?php if (!$magewire->customerCardIsSelected && $oneClickEnabled): ?>
                <div class="field save-cc">
                    <div class="control">
                        <input
                            type="checkbox"
                            name="payment[create_oneclick]"
                            value="1"
                            class="checkbox"
                            id="hipay_hosted_create_oneclick"
                        />
                        <label class="label" for="hipay_hosted_create_oneclick">
                            <span><?= $escaper->escapeHtml(__('Save this card for future use')) ?></span>
                        </label>
                    </div>
                </div>
            <?php endif; ?>
        </div>

        <div class="notice-message mt-2 hidden" wire:ignore>
            <span><?= $escaper->escapeHtml(__('You will be redirect to payment page after submit order.')) ?></span>
        </div>

        <div class="actions-toolbar iframe-continue mt-2" wire:ignore>
            <button
                data-role="review-save"
                type="button"
                class="btn btn-primary justify-center py-2.5"
            >
                <span><?= $escaper->escapeHtml(__('Continue')) ?></span>
            </button>
        </div>

        <div class="iframe-container" style="display:none;" wire:ignore>
            <div id="iframe-warning" class="message notice">
                <div>
                    <span>
                        <?= $escaper->escapeHtml(
                            __('Please do not refresh the page until you complete payment.')
                        ) ?>
                    </span>
                </div>
            </div>
            <div class="iframe-wrapper" wire:ignore>
                <iframe
                    id="hosted-iframe"
                    data-container="hipay-hosted-iframe"
                    class="hipay_hosted iframe"
                    border="0"
                    title="HiPay Hosted Page"
                    sandbox="allow-modals allow-top-navigation allow-same-origin allow-scripts allow-forms"
                ></iframe>
            </div>
        </div>
    </div>
</div>
