<?php
/**
 * HiPay Fullservice Magento - Hyvä Checkout
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Apache 2.0 Licence
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * @copyright Copyright (c) 2024 - HiPay
 * @license   http://www.apache.org/licenses/LICENSE-2.0 Apache 2.0 Licence
 */

declare(strict_types=1);

use HiPay\FullserviceHyvaCheckout\Magewire\PayPalMethod;
use HiPay\FullserviceHyvaCheckout\ViewModel\Config;
use HiPay\FullserviceMagento\Model\Method\Paypal;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Csp\ViewModel\NonceProvider;
use Magento\Framework\Escaper;

/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */
/** @var PayPalMethod $magewire */
$configViewModel = $viewModels->require(Config::class);
$nonceViewModel = $viewModels->require(NonceProvider::class);
$isPayPalV2 = (bool) $configViewModel->isPayPalV2();

$quote = (array) $magewire->getQuoteInformations();
$amount = (string) ($quote['base_total'] ?? '0');
$currency = (string) ($quote['currency_code'] ?? 'EUR');
?>
<div
    x-data="hipayCheckoutPaypalApi"
    data-wire-id="<?= $escaper->escapeHtmlAttr($magewire->getId()) ?>"
    data-method="<?= $escaper->escapeHtmlAttr(Paypal::HIPAY_METHOD_CODE) ?>"
    data-is-paypal-v2="<?= $isPayPalV2 ? '1' : '0' ?>"
    data-toc-enabled="<?= $configViewModel->isTOCEnabled() ? '1' : '0' ?>"
    data-config="<?= $escaper->escapeHtmlAttr($configViewModel->getSerializedConfig()) ?>"
    data-paypal-config="<?= $escaper->escapeHtmlAttr($configViewModel->getSerializedPayPalConfig()) ?>"
    data-api-env="<?= $escaper->escapeHtmlAttr((string) $configViewModel->getApiEnv()) ?>"
    data-api-username-token-js="<?= $escaper->escapeHtmlAttr((string) $configViewModel->getApiUsernameTokenJs()) ?>"
    data-api-password-token-js="<?= $escaper->escapeHtmlAttr((string) $configViewModel->getApiPasswordTokenJs()) ?>"
    data-amount="<?= $escaper->escapeHtmlAttr($amount) ?>"
    data-currency="<?= $escaper->escapeHtmlAttr($currency) ?>"
    data-csp-nonce="<?= $escaper->escapeHtmlAttr((string)$nonceViewModel->getNonce()) ?>"
    data-hipay-shipping-validation="<?=
    $escaper->escapeHtmlAttr(
        json_encode($magewire->validateCustomerShippingInformation() ?? null)
    ) ?>"
    data-i18n-fields="<?= $escaper->escapeHtmlAttr(json_encode([
        'address'  => (string) __('address'),
        'zipCode' => (string) __('postal code'),
        'city'     => (string) __('city'),
        'country'  => (string) __('country'),
    ])) ?>"
>
    <?php if (!$isPayPalV2): ?>
        <div class="text-sm text-slate-600">
            <?= $escaper->escapeHtml(__('You will be redirected to the payment page after submitting the order.')) ?>
        </div>
    <?php else: ?>
        <?php if ((int) $configViewModel->isTOCEnabled()): ?>
            <div
                id="paypal-toc-message"
                data-role="paypal-agreements-warning"
                class="hidden mt-2 text-sm text-red-600"
                role="alert"
                aria-live="polite"
            >
                <?= $escaper->escapeHtml(__('Please agree with the terms of conditions below')) ?>
            </div>
        <?php endif; ?>

        <div
            id="paypal-required-fields-message"
            data-role="paypal-required-fields-warning"
            class="hidden mt-2 text-sm text-red-600"
            role="alert"
            aria-live="polite"
        >
            <?= $escaper->escapeHtml(__('Please complete the required fields to pay with PayPal.')) ?>
        </div>

        <div id="paypal-invalid-address"
             data-role="paypal-invalid-address"
             class="hidden mt-2 text-sm text-red-600"
             role="alert" aria-live="polite">
            <span>
                <?= $escaper->escapeHtml(
                    __('Invalid delivery address. Please check or correct the following fields:')
                ) ?>
            </span>
            <strong><span data-role="paypal-invalid-address-fields"></span></strong>
        </div>

        <div id="paypal-field" data-role="paypal-field" wire:ignore class="!w-2/3 pr-4 mx-auto"></div>
    <?php endif; ?>
</div>
